### ISSUE TITLE
Design Docs To Do List - Wiki, Features, Schema, and Sample State

### ISSUE THREAD

**Issue by mwmadsen67** [JasmineKobata/Fullstack-Project#1]
Hi Jasmine, here is checklist for going through your docs. I'll go through what you have so far and leave comments underneath. 

---

# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [ ] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [ ] all links route the correct page

---

# Feature List

- [x] Should have 7 Features.
    - [x] 3 of those are User Auth, render.io, and Production README.
    - [x] The other 4 are from the [Feature/MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [ ] Contains a description sentence of the app
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each feature
- [x] Correctly formatted
    - [x] features are listed in an ordered list
    - [x] Each feature is broken down into bullet points

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [ ] Correctly formatted
    - [ ] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [ ] Top level slices
        - [x] `entities`
        - [ ] `session`
        - [ ] `errors` (here or in `ui`)
        - [ ] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by mwmadsen67** [comment]
Hi, just reviewing your docs so far, I will leave comments below:

Homepage and Feature List are missing, make sure to complete this! Deciding on which features to work will help plan the rest of the app.

Schema:
- users looks good
- trails I think might need more information. I would check out the all trails website to see what other columns you want to include, like elevation and description. I would think about longitude and latitude as well, in order to connect trails to maps
- The other thing to think about is whether or not you want a parks table as well, since that is part of the website.
- reviews looks good
- if you are going to have a tags table with trails, then you might need a joins table as well. Since trails can have many tags, and tags can be on many trails, it is a many to many relationship. Let me know if you have any questions on setting that up.

Alright, that is all of my comments for now, again please let me know if you have questions and we can either meet to talk about it or we can message on here.

**Comment by cjc473** [comment]
Hi Jasmine, here are the remaining changes:

Homepage:
* Change the welcome message to include your project name.
* Add the placeholder live link.
* Created a bulleted list of links to each page (see GG anouncements on 2/16 for formatting)

Features:
* Add a one sentence description of the App.
* Add a bullet for Search (for example, do users search parks and trails by name? tags?)

Schema:
* In trails, add not null and indexed to park_id.
* I see there isn't a tags table anymore. If you didn't want to have one, you could have a tags column in your trails with a string datatype. Each tag can be separated by a space. When you search for tails by tag, you can run a SQL query that searches for that tag inside the string. This is up to you though, depending on whether you want tags as part of your search feature.

Sample State:
* Need session, errors, and ui.
* Should wrap the entire section in a code block
* Remove chirps from entities (lol)
